name: Upload Weatherworld to S3 bucket

on:
    push:
        branches:
            - main
            - dev_env
            - uat_env

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: AKIAQZRPDMJIKUSS3RFF
                aws-secret-access-key: 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
                aws-region: ap-southeast-2

            - name: Install dependencies and run tests
              run: npm install && npm run test

            - name: Build weatherworld
              run: api_key=ff32503c409ca34cb56a8072fe16c743 npm run build

            - name: Deploy weatherworld stattic files to S3
              run: aws s3 sync ./build/ s3://weatherworld
               --delete
              
            
              
              