name: Upload Weatherworld to S3 bucket

on:
    push:
        branches:
            - main
            - dev_env
            - uat_env

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: ${{ secrets.AWS_REGION}}

            - name: Install dependencies and run tests
              run: npm install && npm run test

            - name: Build weatherworld
              run: REACT_APP_API_KEY=${{ secrets.API_KEY}} npm run build

            - name: Deploy weatherworld static files to S3
              run: aws s3 sync ./build/ s3://${{ secrets.BUCKET}}
               --delete
              
            
              
              